"""
In-Memory Deduplicator - P8-08e Component

This module implements front-line deduplication that happens immediately
when findings are generated by the Agent, BEFORE they enter the processing pipeline.

This is the FOURTH line of defense in the P8-08 architecture:
- Deduplicates findings within the same file
- Deduplicates findings across the call chain
- Works IN MEMORY (no LLM calls required)
- Reduces input to P6-17 global deduplicator

Relationship with P6-17:
- P6-17 (ClusterBasedDeduplicator): Global dedup across all engines, uses LLM
- P8-08e (InMemoryDeduplicator): Front-line dedup per file, rule-based

Integration Point:
    Called in OpenCodeAgent._parse_llm_response() after parsing findings.
"""

import hashlib
import logging
from dataclasses import dataclass

from src.layers.l3_analysis.models import Finding


@dataclass
class DeduplicationStats:
    """Statistics for deduplication operations."""
    total_input: int = 0
    total_output: int = 0
    file_filtered: int = 0
    chain_filtered: int = 0

    def reduction_rate(self) -> float:
        """Calculate reduction rate (0-1)."""
        if self.total_input == 0:
            return 0.0
        return 1.0 - (self.total_output / self.total_input)


class InMemoryDeduplicator:
    """
    In-memory finding deduplicator.

    This deduplicator operates on findings as they are produced,
    providing immediate deduplication without expensive LLM calls.

    Deduplication Strategy:
    1. File-level dedup: Same file + same line = keep highest score
    2. Call-chain dedup: Same vulnerability type = keep first/highest

    The deduplication is SEMANTIC, not just positional:
    - Uses rule_id, sink, and source to identify same vulnerability
    - Preserves the finding with highest final_score
    """

    def __init__(self):
        """Initialize the in-memory deduplicator."""
        self.logger = logging.getLogger(__name__)

        # File-level dedup cache: {(file, line): finding}
        self.current_file_cache: dict[tuple[str, int], Finding] = {}

        # Call-chain dedup cache: {vuln_hash: finding}
        self.call_chain_cache: dict[str, Finding] = {}

        # Statistics
        self.stats = DeduplicationStats()

    def deduplicate_findings(
        self,
        findings: list[Finding],
        file_path: str,
        clear_file_cache: bool = True,
    ) -> list[Finding]:
        """
        Deduplicate findings from a single file scan.

        Args:
            findings: List of findings from the file scan.
            file_path: Path to the file being scanned.
            clear_file_cache: Whether to clear file cache after processing.

        Returns:
            Deduplicated list of findings.
        """
        self.stats.total_input += len(findings)
        deduped = []

        # Stage 1: call-chain deduplication (cross-file, same vuln type).
        # Keep the highest-scored finding per vuln hash; drop duplicates.
        survivors: list[Finding] = []
        for finding in findings:
            vuln_hash = self._get_vulnerability_hash(finding)
            if vuln_hash in self.call_chain_cache:
                existing = self.call_chain_cache[vuln_hash]
                new_score = finding.final_score or 0
                old_score = existing.final_score or 0
                if new_score > old_score:
                    # New finding is better: replace the cached one and swap it
                    # out of the current output set too.
                    self.call_chain_cache[vuln_hash] = finding
                    if existing in survivors:
                        survivors.remove(existing)
                    survivors.append(finding)
                else:
                    # Duplicate of an already-kept (equal/higher) finding: drop it.
                    self.stats.chain_filtered += 1
            else:
                self.call_chain_cache[vuln_hash] = finding
                survivors.append(finding)

        # Stage 2: file-level deduplication (same file + same line).
        # Keep the highest-scored finding per (file, line); drop duplicates.
        for finding in survivors:
            line_key = (file_path, finding.location.line)
            if line_key in self.current_file_cache:
                existing = self.current_file_cache[line_key]
                new_score = finding.final_score or 0
                old_score = existing.final_score or 0
                if new_score > old_score:
                    self.current_file_cache[line_key] = finding
                    if existing in deduped:
                        deduped.remove(existing)
                    deduped.append(finding)
                else:
                    # Same position with an equal/higher-scored finding already kept.
                    self.stats.file_filtered += 1
            else:
                self.current_file_cache[line_key] = finding
                deduped.append(finding)

        self.stats.total_output += len(deduped)

        # Clear file-level cache (for next file)
        if clear_file_cache:
            self.current_file_cache.clear()
        # Note: Keep call_chain_cache across files for cross-file dedup

        self.logger.info(
            f"In-memory deduplication: {len(findings)} -> {len(deduped)} findings "
            f"({self.stats.reduction_rate():.1%} reduction)"
        )

        return deduped

    def _get_vulnerability_hash(self, finding: Finding) -> str:
        """
        Generate a semantic hash for vulnerability identification.

        The hash identifies the SAME vulnerability across different
        reporting levels in the call chain.

        Components used:
        - rule_id: Vulnerability type (sql_injection, xss, etc.)
        - sink: The dangerous function/method
        - source: The tainted data source (if available)

        Components NOT used (intentionally):
        - line number: Same vuln appears at different levels
        - file path: Same vuln in different files in call chain
        - message text: Different engines phrase differently

        Args:
            finding: The finding to hash.

        Returns:
            8-character hex hash string.
        """
        # Extract components
        rule_id = finding.rule_id or "unknown"

        # Extract sink (dangerous function)
        sink = self._extract_sink(finding)

        # Extract source (if available)
        source = self._extract_source(finding)

        # Combine: rule_id + sink + source
        combined = f"{rule_id}:{sink}:{source}"

        # Generate hash
        hash_value = hashlib.md5(combined.encode()).hexdigest()[:8]

        return f"mem_{hash_value}"

    def _extract_sink(self, finding: Finding) -> str:
        """
        Extract the sink (dangerous function) from a finding.

        The sink is where the vulnerability manifests - the dangerous
        operation that exploits the tainted data.

        Args:
            finding: The finding to analyze.

        Returns:
            Sink function name or "unknown".
        """
        # Try to get from metadata
        if finding.metadata:
            sink = finding.metadata.get("sink")
            if sink:
                return str(sink)

            # Try dataflow information
            dataflow = finding.metadata.get("dataflow")
            if isinstance(dataflow, dict):
                sink = dataflow.get("sink")
                if sink:
                    return str(sink)

        # Extract from code snippet
        snippet = (finding.location.snippet or "").strip()

        # Look for dangerous function calls
        dangerous_patterns = [
            r"\.execute\(", r"\.exec\(", r"\.query\(", r"\.run\(",
            r"eval\(", r"exec\(", r"system\(",
            r"open\(", r"read\(", r"write\(",
            r"innerHTML", "dangerouslySetInnerHTML",
        ]

        import re
        for pattern in dangerous_patterns:
            match = re.search(pattern, snippet, re.IGNORECASE)
            if match:
                return match.group(0)

        # Fallback: extract function name from snippet
        # Look for word followed by (
        func_match = re.search(r"(\w+)\s*\(", snippet)
        if func_match:
            return func_match.group(1)

        return "unknown"

    def _extract_source(self, finding: Finding) -> str:
        """
        Extract the source (tainted data origin) from a finding.

        The source is where untrusted data enters the system.

        Args:
            finding: The finding to analyze.

        Returns:
            Source identifier or "unknown".
        """
        # Try to get from metadata
        if finding.metadata:
            source = finding.metadata.get("source")
            if source:
                return str(source)

            source = finding.metadata.get("taint_source")
            if source:
                return str(source)

            # Try dataflow information
            dataflow = finding.metadata.get("dataflow")
            if isinstance(dataflow, dict):
                source = dataflow.get("source")
                if source:
                    return str(source)

        # Try to extract from description
        desc = (finding.description or "").lower()

        # Common sources
        source_indicators = {
            "user input": "user",
            "request parameter": "request",
            "query parameter": "query",
            "form data": "form",
            "http header": "header",
            "cookie": "cookie",
            "environment variable": "env",
        }

        for indicator, name in source_indicators.items():
            if indicator in desc:
                return name

        return "unknown"

    def get_stats(self) -> DeduplicationStats:
        """Get deduplication statistics."""
        return self.stats

    def clear_call_chain_cache(self):
        """Clear the call-chain cache (between scans)."""
        self.call_chain_cache.clear()

    def clear_all_caches(self):
        """Clear all caches."""
        self.current_file_cache.clear()
        self.call_chain_cache.clear()


# Convenience function
def deduplicate_in_memory(
    findings: list[Finding],
    file_path: str,
) -> list[Finding]:
    """
    Convenience function for in-memory deduplication.

    Args:
        findings: List of findings from a file scan.
        file_path: Path to the file.

    Returns:
        Deduplicated list of findings.
    """
    deduplicator = InMemoryDeduplicator()
    return deduplicator.deduplicate_findings(findings, file_path)
"""
    P8-08e: In-Memory Deduplicator - front-line deduplication

    Components:
    - InMemoryDeduplicator: Main deduplicator class
    - DeduplicationStats: Statistics tracking
    - deduplicate_in_memory: Convenience function

    Integration:
        Called in OpenCodeAgent after parsing findings,
        before they enter the global processing pipeline.
"""
