"""
Unit tests for FilePreFilter - P8-08a component.

Tests cover all filtering criteria:
1. Configuration file detection
2. Auto-generated code detection
3. Executable code detection
4. Attack surface reachability
"""

import pytest

from src.layers.l3_analysis.pre_filter.file_pre_filter import (
    FilePreFilter,
    FilterResult,
    should_analyze_file,
)


class TestFilePreFilter:
    """Test suite for FilePreFilter class."""

    def test_init_default_mode(self):
        """Test initialization with default (non-strict) mode."""
        filter_obj = FilePreFilter()
        assert filter_obj.strict_mode is False

    def test_init_strict_mode(self):
        """Test initialization with strict mode."""
        filter_obj = FilePreFilter(strict_mode=True)
        assert filter_obj.strict_mode is True


class TestConfigFileDetection:
    """Test configuration file detection."""

    def test_yaml_config_file(self):
        """Test YAML configuration files are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="config/app.yaml",
            code="some: value",
        )

        assert result.should_analyze is False
        assert "Configuration file" in result.reason

    def test_json_config_file(self):
        """Test JSON configuration files are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="config/settings.json",
            code='{"key": "value"}',
        )

        assert result.should_analyze is False
        assert "Configuration file" in result.reason

    def test_dockerfile(self):
        """Test Dockerfile is filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="Dockerfile",
            code="FROM python:3.10",
        )

        assert result.should_analyze is False

    def test_docker_compose(self):
        """Test docker-compose files are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="docker-compose.yml",
            code="services:\n  web:",
        )

        assert result.should_analyze is False

    def test_package_json(self):
        """Test package.json is filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="package.json",
            code='{"name": "test"}',
        )

        assert result.should_analyze is False

    def test_pom_xml(self):
        """Test Maven pom.xml is filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="pom.xml",
            code="<project></project>",
        )

        assert result.should_analyze is False

    def test_config_directory(self):
        """Test files in config/ directory are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="config/database.py",
            code="DB_HOST = 'localhost'",
        )

        assert result.should_analyze is False

    def test_python_source_file_passes(self):
        """Test regular Python source file passes."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="app/views/user_view.py",
            code="def get_user(id):\n    return db.query(id)",
        )

        assert result.should_analyze is True


class TestGeneratedCodeDetection:
    """Test auto-generated code detection."""

    def test_do_not_edit_marker(self):
        """Test files with 'DO NOT EDIT' marker are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="generated/models.py",
            code="# DO NOT EDIT\nclass User:\n    pass",
        )

        assert result.should_analyze is False
        assert "Auto-generated" in result.reason

    def test_auto_generated_marker(self):
        """Test files with 'Auto-generated' marker are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="src/types.ts",
            code="// Auto-generated by build script\ninterface User {}",
        )

        assert result.should_analyze is False

    def test_generated_by_marker(self):
        """Test files with 'Generated by' marker are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="pb/user.proto.ts",
            code="// Generated by protoc\nmessage User {}",
        )

        assert result.should_analyze is False

    def test_at_generated_marker(self):
        """Test files with //@generated marker are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="types.generated.ts",
            code="/* @generated */\ntype User = {}",
        )

        assert result.should_analyze is False

    def test_regular_code_passes(self):
        """Test regular handwritten code passes."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="app/handlers/user.py",
            code="def get_user():\n    return db.query()",
        )

        assert result.should_analyze is True


class TestExecutableCodeDetection:
    """Test executable code detection."""

    def test_only_constants_filtered(self):
        """Test files with only constant definitions are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="constants.py",
            code="MAX_USERS = 100\nDEFAULT_TIMEOUT = 30",
        )

        assert result.should_analyze is False
        assert "No executable code" in result.reason

    def test_only_type_definitions_filtered(self):
        """Test files with only type definitions might be filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="types.py",
            code="class UserType:\n    ADMIN = 'admin'\n    USER = 'user'",
        )

        # Types alone might be filtered (depends on implementation)
        # This test documents the behavior

    def test_python_function_passes(self):
        """Test Python files with functions pass."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="views.py",
            code="def get_user(id):\n    return db.query(User, id)",
        )

        assert result.should_analyze is True

    def test_java_method_passes(self):
        """Test Java files with methods pass."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="UserController.java",
            code="public User getUser(Long id) {\n    return repository.findById(id);\n}",
        )

        assert result.should_analyze is True

    def test_javascript_function_passes(self):
        """Test JavaScript files with functions pass."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="routes.js",
            code="app.get('/users', (req, res) => {\n    res.json(users);\n});",
        )

        assert result.should_analyze is True

    def test_dangerous_operation_passes(self):
        """Test files with dangerous operations pass."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="utils.py",
            code="def execute(cmd):\n    os.system(cmd)",
        )

        assert result.should_analyze is True

    def test_empty_file_filtered(self):
        """Test empty files are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="empty.py",
            code="",
        )

        assert result.should_analyze is False

    def test_very_small_file_filtered(self):
        """Test very small files are filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="tiny.py",
            code="# just a comment",
        )

        assert result.should_analyze is False


class TestAttackSurfaceReachability:
    """Test attack surface reachability detection."""

    def test_controller_file_passes(self):
        """Test controller files pass."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="app/controllers/UserController.java",
            code="public class UserController {}",
            attack_surface=["/api/users"],
        )

        assert result.should_analyze is True

    def test_handler_file_passes(self):
        """Test handler files pass."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="handlers/user_handler.go",
            code="func GetUserHandler() {}",
            attack_surface=["/users"],
        )

        assert result.should_analyze is True

    def test_view_file_passes(self):
        """Test view files pass."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="views/user_view.py",
            code="def user_list(): pass",
            attack_surface=["/users"],
        )

        assert result.should_analyze is True

    def test_util_file_strict_mode_filtered(self):
        """Test utility files filtered in strict mode."""
        filter_obj = FilePreFilter(strict_mode=True)

        result = filter_obj.should_analyze(
            file_path="utils/string_helper.py",
            code="def format_string(s): return s.upper()",
            attack_surface=["/api/users"],
        )

        assert result.should_analyze is False
        assert "attack surface" in result.reason

    def test_util_file_non_strict_passes(self):
        """Test utility files pass in non-strict mode."""
        filter_obj = FilePreFilter(strict_mode=False)

        result = filter_obj.should_analyze(
            file_path="utils/string_helper.py",
            code="def format_string(s): return s.upper()",
            attack_surface=["/api/users"],
        )

        # Non-strict mode analyzes anyway
        assert result.should_analyze is True

    def test_no_attack_surface_info_passes(self):
        """Test files pass when no attack surface info provided."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="utils/helper.py",
            code="def help(): pass",
            attack_surface=None,
        )

        assert result.should_analyze is True

    def test_web_framework_pattern_passes(self):
        """Test files with web framework patterns pass."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="app/routes.py",
            code="@app.route('/users')\ndef get_users(): pass",
            attack_surface=["/api/users"],
        )

        assert result.should_analyze is True


class TestConvenienceFunction:
    """Test the should_analyze_file convenience function."""

    def test_returns_tuple(self):
        """Test function returns (bool, str) tuple."""
        should_analyze, reason = should_analyze_file(
            file_path="app.py",
            code="def main(): pass",
        )

        assert isinstance(should_analyze, bool)
        assert isinstance(reason, str)

    def test_with_path_object(self):
        """Test function works with Path object."""
        from pathlib import Path

        should_analyze, reason = should_analyze_file(
            file_path=Path("app.py"),
            code="def main(): pass",
        )

        assert should_analyze is True


class TestIntegrationScenarios:
    """Integration tests for real-world scenarios."""

    def test_flask_route_file_passes(self):
        """Test Flask route file passes all checks."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="app/routes/user_routes.py",
            code="""
from flask import Flask, request
app = Flask(__name__)

@app.route('/users/<int:id>')
def get_user(id):
    return {'id': id}
""",
            attack_surface=["/users"],
        )

        assert result.should_analyze is True
        assert result.reason == "Pass pre-filter checks"

    def test_migrations_folder_filtered(self):
        """Test migrations folder is filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="migrations/12345_initial.py",
            code="def upgrade(): pass\ndef downgrade(): pass",
        )

        # Migrations in migrations/ folder should be filtered
        assert result.should_analyze is False

    def test_proto_generated_file_filtered(self):
        """Test protobuf generated file is filtered."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="generated/user_pb2.py",
            code="# Generated by protoc\n# DO NOT EDIT\n",
        )

        assert result.should_analyze is False
        assert "Auto-generated" in result.reason

    def test_tests_folder_passes(self):
        """Test files in tests/ folder."""
        filter_obj = FilePreFilter()

        result = filter_obj.should_analyze(
            file_path="tests/test_user.py",
            code="def test_user(): assert True",
        )

        # Tests might be analyzed (depending on policy)
        # This test documents current behavior
